services:
  redpanda:
    container_name: redpanda
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.12
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      # Address the broker advertises to clients that connect to the Kafka API.
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      # Redpanda brokers use the RPC API to communicate with each other internally.
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --set auto_create_topics_enabled=true
    ports:
      - 18081:8081
      - 18082:8082
      - 19092:9092
      - 19644:9644
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s

  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.7.2
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
        connect:
          enabled: true
          clusters:
            - name: local-connect-cluster
              url: http://connect:8083
    ports:
      - 8080:8080
    depends_on:
      - redpanda

  influxdb-v2-source:
    container_name: influxdb-v2-source
    restart: always
    build:
      context: "./influxdb_v2_source"
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
      - OUTPUT_TOPIC=influxdb-v2-data
      - INFLUXDB_HOST=
      - INFLUXDB_ORG=
      - INFLUXDB_BUCKET=
      - INFLUXDB_TOKEN=
      - TASK_INTERVAL=30d
    depends_on:
      - redpanda

  influxdb-v3-sink:
    container_name: influxdb-v3-sink
    restart: always
    build:
      context: "./influxdb_v3_sink"
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
      - INPUT_TOPIC=influxdb-v2-data
      - INFLUXDB_HOST=https://us-east-1-1.aws.cloud2.influxdata.com/
      - INFLUXDB_ORG=
      - INFLUXDB_BUCKET=
      - INFLUXDB_TOKEN=
      - INFLUXDB_TAG_KEYS=[]
      - INFLUXDB_FIELD_KEYS=[]
    depends_on:
      - redpanda
