name: InfluxDB v2 Source
language: python
variables:
  - name: OUTPUT_TOPIC
    inputType: OutputTopic
    description: The output topic to store the results fetched from the InfluxDB v2 queries
    required: true
    value: influxdb-v2-data
  - name: INFLUXDB_HOST
    inputType: FreeText
    description: The address of the InfluxDB v2 instance
    required: true
    value: <INFLUXDB_HOST>
  - name: INFLUXDB_ORG
    inputType: FreeText
    description: The configured organization in the InfluxDB v2 instance
    required: true
    value: <INFLUXDB_ORG>
  - name: INFLUXDB_BUCKET
    inputType: FreeText
    description: The name of the InfluxDB v2 bucket that stores the source data to be synced
    required: true
    value: <INFLUXDB_BUCKET>
  - name: INFLUXDB_TOKEN
    inputType: Secret
    description: The configured API Token to access the InfluxDB v2 instance (defined as a secret in Quix)
    required: true
    secretKey: INFLUXDB_TOKEN
  - name: TASK_INTERVAL
    inputType: FreeText
    description: Defines both how often the query should be run against the database and the max age of the data to return. See the InfluxDB documentation for a full list of valid interval values
    required: false
    value: 1m
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
