name: InfluxDB V2 Data Source
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: influxv2-data
    required: true
  - name: INFLUXDB_ORG
    inputType: FreeText
    description: ''
    defaultValue: DevRel
    required: true
  - name: INFLUXDB_HOST
    inputType: FreeText
    description: ''
    defaultValue: https://us-east-1-1.aws.cloud2.influxdata.com
    required: true
  - name: task_interval
    inputType: FreeText
    description: ''
    defaultValue: 5m
    required: false
  - name: INFLUXDB_BUCKET
    inputType: FreeText
    description: ''
    defaultValue: quix
    required: true
  - name: INFLUXDB_TOKEN
    inputType: Secret
    description: ''
    defaultValue: influx_db
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
